# Generated by Django 4.1.7 on 2023-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_chaudiere_bruleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaudiere',
            name='bruleur',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='chaudiere',
            name='nbPompe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaudiere',
            name='nbV2V',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaufferie',
            name='nbChaudiere',
            field=models.IntegerField(),
        ),
    ]
