# Generated by Django 4.1.7 on 2023-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_chaudiere_bruleur_alter_chaudiere_nbpompe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chaudiere',
            name='bruleur',
        ),
        migrations.RemoveField(
            model_name='chaudiere',
            name='nbPompe',
        ),
        migrations.AddField(
            model_name='chaudiere',
            name='nbBruleur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chaudiere',
            name='nbPpe',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chaudiere',
            name='nomChaud',
            field=models.CharField(default='Chaudière <django.db.models.fields.IntegerField>', max_length=200),
        ),
        migrations.AddField(
            model_name='chaudiere',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chaudiere',
            name='nbV2V',
            field=models.IntegerField(default=1),
        ),
    ]
