# Generated by Django 4.1.7 on 2023-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_chaufferie_nbcirccst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircCst',
        ),
        migrations.RemoveField(
            model_name='chaudiere',
            name='nbBruleur',
        ),
        migrations.AddField(
            model_name='chaudiere',
            name='bruleurPres',
            field=models.BooleanField(default=False),
        ),
    ]
