# Generated by Django 4.1.7 on 2023-04-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_chaudiere_bruleurpres'),
    ]

    operations = [
        migrations.AddField(
            model_name='circreg',
            name='nbAmb',
            field=models.IntegerField(default=1),
        ),
    ]
