# Generated by Django 4.1.7 on 2023-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_ecs_nbdef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaudiere',
            name='nbTemp',
            field=models.IntegerField(default=2),
        ),
    ]
