# Generated by Django 4.1.7 on 2023-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_point_supp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaufferie',
            name='nomInstal',
            field=models.CharField(default='Nouvelle installation', max_length=200),
        ),
    ]
