# Generated by Django 4.1.7 on 2023-04-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_chaufferie_nominstal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='nomGen',
            field=models.CharField(default='Général', max_length=200),
        ),
        migrations.AlterField(
            model_name='point',
            name='TC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='TM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='TR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='TS',
            field=models.IntegerField(default=0),
        ),
    ]
