# Generated by Django 4.1.7 on 2023-08-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaudiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomChaud', models.CharField(default='Chaudière <django.db.models.fields.IntegerField>', max_length=200)),
                ('nbTemp', models.IntegerField(default=2)),
                ('nbDef', models.IntegerField(default=1)),
                ('nbV2V', models.IntegerField(default=1)),
                ('nbPpe', models.IntegerField(default=1)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chaufferie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200)),
                ('nomInstal', models.CharField(default='Nouvelle installation', max_length=200)),
                ('nbChaudiere', models.IntegerField(default=1)),
                ('nbDivers', models.IntegerField(default=0)),
                ('nbCircReg', models.IntegerField(default=1)),
                ('ECSpres', models.BooleanField(default=False)),
                ('ECSprepa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomCirc', models.CharField(default='Circuit Régulé <django.db.models.fields.IntegerField>', max_length=200)),
                ('nbTemp', models.IntegerField(default=1)),
                ('nbAmb', models.IntegerField(default=1)),
                ('nbV3V', models.IntegerField(default=1)),
                ('nbPpe', models.IntegerField(default=2)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Divers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomDivers', models.CharField(default='Divers <django.db.models.fields.IntegerField>', max_length=200)),
                ('nbV2V', models.IntegerField(default=1)),
                ('nbPpe', models.IntegerField(default=1)),
                ('nbTSsup', models.IntegerField(default=1)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ECS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomECS', models.CharField(default='ECS <django.db.models.fields.IntegerField>', max_length=200)),
                ('nbDef', models.IntegerField(default=1)),
                ('nbTemp', models.IntegerField(default=1)),
                ('nbBallon', models.IntegerField(default=1)),
                ('nbV3V', models.IntegerField(default=1)),
                ('nbPpe', models.IntegerField(default=2)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomGen', models.CharField(default='Général', max_length=200)),
                ('nbDefaut', models.IntegerField(default=1)),
                ('nbTempExt', models.IntegerField(default=1)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='listePacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(default='', max_length=200)),
                ('AI', models.IntegerField()),
                ('DI', models.IntegerField()),
                ('AO', models.IntegerField()),
                ('DO', models.IntegerField()),
                ('priceWIT', models.FloatField()),
                ('priceTREND', models.FloatField()),
                ('priceDISTECH', models.FloatField()),
                ('priceSOFREL', models.FloatField()),
                ('priceMOY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip', models.CharField(default='equipement', max_length=200)),
                ('libelle', models.CharField(default='libellé', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('TM', models.IntegerField(default=0)),
                ('TS', models.IntegerField(default=0)),
                ('TR', models.IntegerField(default=0)),
                ('TC', models.IntegerField(default=0)),
                ('Supp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Amb',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdBal',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdChaud',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdPpe',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdV2V',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdV3V',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='DefPpe',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='FdcV2V',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='SyntDefaut',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
    ]
