# Generated by Django 4.1.7 on 2023-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='Reference',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
