# Generated by Django 4.1.7 on 2023-08-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_pack_packtg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackOPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(default='', max_length=200, unique=True)),
                ('Tamb', models.IntegerField()),
                ('TECS', models.IntegerField()),
                ('pricePAS', models.FloatField()),
                ('priceTamb', models.FloatField()),
                ('priceTECS', models.FloatField()),
                ('priceTOT', models.FloatField()),
            ],
        ),
    ]
