# Generated by Django 4.1.7 on 2023-03-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_chaufferie_delete_automatechaudiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaudiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruleur', models.BooleanField()),
                ('nbPompe', models.IntegerField(max_length=1)),
                ('nbV2V', models.IntegerField(max_length=1)),
            ],
        ),
    ]
