# Generated by Django 4.1.7 on 2023-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_chaudiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaudiere',
            name='bruleur',
            field=models.BooleanField(max_length=1),
        ),
    ]
