# Generated by Django 4.1.7 on 2023-08-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_packopt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotIOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passerelle', models.BooleanField(default=True)),
                ('nbTempAmbIOT', models.IntegerField(default=0)),
                ('nbTemp1EauIOT', models.IntegerField(default=0)),
                ('nbTemp2EauIOT', models.IntegerField(default=0)),
                ('nbCO2IOT', models.IntegerField(default=0)),
                ('nbTLRGazIOT', models.IntegerField(default=0)),
                ('nbTLREauIOT', models.IntegerField(default=0)),
                ('nbTLRElecIOT', models.IntegerField(default=0)),
                ('nbTLRCaloIOT', models.IntegerField(default=0)),
            ],
        ),
    ]
