# Generated by Django 4.1.7 on 2023-08-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_lotiot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotiot',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
