# Generated by Django 4.1.7 on 2023-08-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_lotiot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackIOTUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(default='', max_length=200, unique=True)),
                ('type', models.CharField(default='', max_length=200)),
                ('comment', models.CharField(default='', max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
    ]
