# Generated by Django 4.1.7 on 2023-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_packiotunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
