# Generated by Django 4.1.7 on 2023-03-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_liste_remove_chaudiere_bruleur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liste',
        ),
    ]
