# Generated by Django 4.1.7 on 2023-09-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='packopt',
            name='nbIOTmax',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
