# Generated by Django 4.1.7 on 2023-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_packopt_nbiotmax'),
    ]

    operations = [
        migrations.CreateModel(
            name='carteAutom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200)),
                ('reference', models.CharField(default='', max_length=200, unique=True)),
                ('DI', models.IntegerField()),
                ('AI', models.IntegerField()),
                ('AO', models.IntegerField()),
                ('UI', models.IntegerField()),
                ('UO', models.IntegerField()),
                ('DOR', models.IntegerField()),
                ('DO_UO', models.IntegerField()),
                ('nbEmpl', models.IntegerField()),
                ('extension', models.CharField(default='', max_length=200)),
                ('rs232', models.IntegerField()),
                ('rs485', models.IntegerField()),
                ('ressources', models.IntegerField()),
                ('maxModbus', models.IntegerField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='chaufferie',
            name='ECSprepa',
            field=models.BooleanField(default=False),
        ),
    ]
