# Generated by Django 4.1.7 on 2023-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_carteautom_alter_chaufferie_ecsprepa'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteautom',
            name='Imagerie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='carteautom',
            name='maxMbus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
