# Generated by Django 4.1.7 on 2023-03-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_liste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='point',
        ),
    ]
