# Generated by Django 4.1.7 on 2023-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_carteautom_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteautom',
            name='Imagerie',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='extension',
            field=models.BooleanField(default=False),
        ),
    ]
