# Generated by Django 4.1.7 on 2023-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomDivers', models.CharField(default='Divers <django.db.models.fields.IntegerField>', max_length=200)),
                ('nbV2V', models.IntegerField(default=1)),
                ('nbPpe', models.IntegerField(default=1)),
                ('nbTSsup', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='chaufferie',
            name='nbDivers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chaufferie',
            name='nbChaudiere',
            field=models.IntegerField(default=1),
        ),
    ]
