# Generated by Django 4.1.7 on 2023-03-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_divers_chaufferie_nbdivers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircCst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomCirc', models.CharField(default='Circuit Constant <django.db.models.fields.IntegerField>', max_length=200)),
                ('nbPpe', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='CircReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('nomCirc', models.CharField(default='Circuit Régulé <django.db.models.fields.IntegerField>', max_length=200)),
                ('nbTemp', models.IntegerField(default=1)),
                ('nbV3V', models.IntegerField(default=1)),
                ('nbPpe', models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='chaufferie',
            name='nbCircCst',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chaufferie',
            name='nbCircReg',
            field=models.IntegerField(default=1),
        ),
    ]
