# Generated by Django 4.1.7 on 2023-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_automate_id_automate_carteautom_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteautom',
            name='AI',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='AO',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='DI',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='DO',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='DOR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='DO_UO',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='UI',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='UO',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='maxMbus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='maxModbus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='nbEmpl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='prix',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='ressources',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='rs232',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteautom',
            name='rs485',
            field=models.IntegerField(default=0),
        ),
    ]
