# Generated by Django 4.1.7 on 2023-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_carteautom_ai_alter_carteautom_ao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteautom',
            name='reference',
            field=models.CharField(default='', max_length=200),
        ),
    ]
