# Generated by Django 4.1.7 on 2023-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_carteautom_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200)),
                ('coutAF', models.IntegerField(default=0)),
                ('coutProg', models.IntegerField(default=0)),
                ('coutIHM', models.IntegerField(default=0)),
                ('coutMES', models.IntegerField(default=0)),
                ('coutCRT', models.IntegerField(default=0)),
                ('coutToT', models.IntegerField(default=0)),
            ],
        ),
    ]
