# Generated by Django 4.1.7 on 2023-04-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_chaufferie_ecspres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaufferie',
            name='nbCircCst',
        ),
    ]
