# Generated by Django 4.1.7 on 2023-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='automate',
            name='cout',
            field=models.IntegerField(default=0),
        ),
    ]
