# Generated by Django 4.1.7 on 2023-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_automate_cout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automate',
            name='cout',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='coutAF',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='coutCRT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='coutIHM',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='coutMES',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='coutProg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='coutToT',
            field=models.FloatField(default=0),
        ),
    ]
