# Generated by Django 4.1.7 on 2023-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_automate_cout_alter_prestation_coutaf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaufferie',
            name='nbImp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chaufferie',
            name='nbMbus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chaufferie',
            name='nbModbus',
            field=models.IntegerField(default=0),
        ),
    ]
