# Generated by Django 4.1.7 on 2023-11-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_cptmbus_cptmodbus_point_mbus_point_modbus'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteautom',
            name='marque',
            field=models.CharField(default='', max_length=200),
        ),
    ]
