# Generated by Django 4.1.7 on 2023-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_carteautom_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaufferie',
            name='ecranNec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chaufferie',
            name='modemNec',
            field=models.BooleanField(default=True),
        ),
    ]
