# Generated by Django 4.1.7 on 2023-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_chaufferie_nominstal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaudiere',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chaufferie',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='circreg',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='divers',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ecs',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='general',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='general',
            name='nomGen',
            field=models.CharField(default='Général', max_length=200),
        ),
        migrations.AlterField(
            model_name='point',
            name='TC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='TM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='TR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='TS',
            field=models.IntegerField(default=0),
        ),
    ]
