# Generated by Django 4.1.7 on 2023-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_chaufferie_nbportmodem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automate',
            old_name='cout',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='automate',
            name='carteautom_ptr',
        ),
        migrations.AddField(
            model_name='automate',
            name='AI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='AO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='DI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='DO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='DOR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='DO_UO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='Imagerie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automate',
            name='UI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='UO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automate',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automate',
            name='marque',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='automate',
            name='maxMbus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='maxModbus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='nbEmpl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='reference',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='automate',
            name='ressources',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='rs232',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='rs485',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automate',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
