# Generated by Django 4.1.7 on 2023-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_chaudiere_user_chaufferie_user_circreg_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
