# Generated by Django 4.1.7 on 2023-04-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_liste_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
