# Generated by Django 4.1.7 on 2023-04-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_syntdefaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdChaud',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdPpe',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='DefPpe',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
    ]
