# Generated by Django 4.1.7 on 2023-04-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_cmdv2v_fdcv2v'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amb',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdBal',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='CmdV3V',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.point')),
            ],
            bases=('polls.point',),
        ),
    ]
