# Generated by Django 4.1.7 on 2023-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_amb_cmdbal_cmdv3v_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='listePacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.IntegerField()),
                ('Reference', models.CharField(default='')),
                ('AI', models.IntegerField()),
                ('DI', models.IntegerField()),
                ('AO', models.IntegerField()),
                ('DO', models.IntegerField()),
                ('priceWIT', models.FloatField()),
                ('priceTREND', models.FloatField()),
                ('priceDISTECH', models.FloatField()),
                ('priceSOFREL', models.FloatField()),
                ('priceMOY', models.FloatField()),
            ],
        ),
    ]
