# Generated by Django 4.1.7 on 2023-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_listepacks_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
