# Generated by Django 4.1.7 on 2023-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_alter_pack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listepacks',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
