# Generated by Django 4.1.7 on 2023-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_alter_listepacks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listepacks',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pack',
            name='Reference',
            field=models.CharField(default='', max_length=200),
        ),
    ]
